version: '2'

services:
    zookeeper:
        image: zookeeper
        restart: always
        ports:
            - 2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zookeeper:2888:3888

    mesos-master:
        image: mesoscloud/mesos-master:0.28.1-centos-7
        restart: always
        hostname: mesos-master
        ports:
            - 5050:5050
        environment:
            MESOS_QUORUM: 1
            MESOS_ZK: zk://zookeeper:2181/mesos
        depends_on:
         - zookeeper

    mesos-slave:
        image: mesoscloud/mesos-slave:0.28.1-centos-7
        restart: always
        hostname: mesos-slave
        privileged: true
        volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup
            - /opt/nerve/var/run/docker.sock:/var/run/docker.sock
        environment:
            MESOS_QUORUM: 1
            MESOS_MASTER: zk://zookeeper:2181/mesos
            MESOS_CONTAINERIZERS: docker,mesos
            MESOS_EXECUTOR_REGISTRATION_TIMEOUT: '5mins'
        depends_on:
         - zookeeper
         - mesos-master

    marathon:
        image: mesoscloud/marathon:1.1.1-centos-7
        restart: always
        hostname: marathon
        ports:
             - 8080:8080
        environment:
            MARATHON_MASTER: zk://zookeeper:2181/mesos
            MARATHON_ZK: zk://zookeeper:2181/marathon
        ulimits:
             nofile: 262144
        depends_on:
         - zookeeper
         - mesos-master
         - mesos-slave
